GET {{content_host}}/content/course-category/tree-nodes?root=1

###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
content-type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}
### 创建课程
POST {{content_host}}/content/course?companyId=1232141425
Content-Type: application/json

{
  "charge": "201001",
  "price": -1,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 根据id查询课程信息
GET {{content_host}}/content/course/40

### 根据id删除课程计划
DELETE {{content_host}}/content/teachplan/296